export const productos = [
    {
        id: 1,
        nombre: "Silla",
        precio: 30,
        categoria: "muebles",
        stock: 25,
        descripcion: "Silla con soporte para piernas",
        img: "",
    },
    {
        id: 2,
        nombre: "Mesa",
        precio: 100,
        categoria: "muebles",
        stock: 15,
        descripcion: "Mesa de madera para comedor",
        img: "",
    },
    {
        id: 3,
        nombre: "Sofa",
        precio: 120,
        categoria: "muebles",
        stock: 20,
        descripcion: "Sofa de 3 puestos",
        img: "",
    },
    {
        id: 4,
        nombre: "Licuadora",
        precio: 20,
        categoria: "electrodomesticos",
        stock: 18,
        descripcion: "Licuadora ultra-potenta",
        img: "",
    },
    {
        id: 5,
        nombre: "Refrigeradora",
        precio: 120,
        categoria: "electrodomesticos",
        stock: 12,
        descripcion: "Refrigeradora de 2 puertas",
        img: "",
    },
];